<!-- SQL문을 작성하기 전에 정상작동 하는지 확인하는 페이지 -->
<!-- STORE(맛집) 데이터 베이스 -->
SELECT * FROM STORE;            <!-- 테이블 안의 데이터 모두 출력 -->

DROP TABLE STORE;               <!-- 테이블 삭제 -->

DELETE FROM STORE WHERE id = 2; <!-- 테이블안의 2번째 행 삭제 -->

ALTER TABLE STORE
    ADD (tag varchar(30));          <!-- 테이블에 새로운 열 추가-->

CREATE TABLE STORE              <!-- 새로운 테이블 생성 -->
(
    id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(10),
    location VARCHAR2(30),
    menu VARCHAR2(10),
    price VARCHAR2(10),
    tag VARCHAR2(30),
    PRIMARY KEY (id)
);

<!-- lodging(숙소) 데이터 베이스 -->
CREATE TABLE LODGING
(
    id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(10),
    location VARCHAR2(30),
    price VARCHAR2(10),
    content TEXT,
    tag VARCHAR2(30),
    PRIMARY KEY (id)
);

<!-- place(장소) 데이터 베이스 -->
CREATE TABLE PLACE
(
    id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    location VARCHAR2(30),
    name VARCHAR2(10),
    content TEXT,
    tag VARCHAR2(30),
    PRIMARY KEY (id)
);




