SELECT * FROM member;

DROP TABLE member;

DELETE FROM member WHERE id = 2;

CREATE TABLE member
(
    id number(5) PRIMARY KEY,
    name varchar2(10)
);

CREATE TABLE member
(
    id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(10),
    PRIMARY KEY (id)
);








